# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Windows

on:
  push:
    branches: [ v1.x ]
  pull_request:
    branches: [ v1.x ]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: windows-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        java-version: 1.12
    - name: Build with Maven
      env:
        GITHUB_USERNAME: williamniemiec
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn --settings settings.xml --file pom.xml install
    - name: JaCoCo
      run: mvn clean jacoco:prepare-agent install jacoco:report
    - uses: codecov/codecov-action@v1
      with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov
